disabled_rules:
  - function_parameter_count
  - identifier_name
included: # paths to include during linting. `--path` is ignored if present.
  - wsm
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
cyclomatic_complexity:
  warning: 15
  error: 20
