use_frameworks!
platform :ios, '9.0'

target 'wsm' do
    pod 'Moya', '~> 8.0.5'
    pod 'TPKeyboardAvoiding'
    pod 'LGSideMenuController'
    pod 'Kingfisher', '~> 3.12.2'
    pod 'SVProgressHUD'    
    pod 'InAppLocalize'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    
    pod 'Permission/Location'    
    pod 'SwiftLint'

    pod 'InAppLocalize'
    pod "Floaty"
    pod 'AFDateHelper', '~> 4.2.4'
    pod 'ObjectMapper'
    pod 'SwiftyUserDefaults'
    pod "PromiseKit", "~> 4.4"
end
