use_frameworks!
platform :ios, '9.0'

target 'wsm' do
    pod 'Moya', '~> 8.0.5'
    pod 'TPKeyboardAvoiding'
    pod 'LGSideMenuController'
    pod 'Kingfisher', '~> 3.12.2'
    pod 'SVProgressHUD'    
    pod 'InAppLocalize'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    
    pod 'Permission/Location'    
    pod 'SwiftLint'

    pod 'InAppLocalize'
    pod "Floaty"
#    pod 'AFDateHelper', '~> 4.2.4'
    pod 'ObjectMapper', '~> 2.2.8’
    pod 'SwiftyUserDefaults'
    pod "PromiseKit", "~> 4.4"
    pod "TextFieldEffects"
#    pod 'ACFloatingTextfield-Swift'
    pod 'MaterialComponents/ShadowElevations'
    pod 'MaterialComponents/ShadowLayer'
    pod 'Validator', '~> 2.1.1'
    pod 'BBBadgeBarButtonItem'
    pod 'Charts'
end
