use_frameworks!
platform :ios, '9.0'

target 'wsm' do
    pod 'Moya', '~> 8.0.5'
    pod 'TPKeyboardAvoiding'
    pod 'LGSideMenuController'
    pod 'Kingfisher', '~> 3.12.2'
    pod 'SVProgressHUD'    
    pod 'InAppLocalize'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'DateToolsSwift'
    pod 'Himotoki'
    pod 'ReactiveCocoa'
    pod 'Permission/Location'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftLint'
    pod 'InAppLocalize'
end
